sudo: required
dist: trusty
services:
  - docker
before_install:
- docker pull blang/latex:ubuntu
script:
- docker run --rm --user="$(id -u):$(id -g)" --net=none -v "$PWD":/data blang/latex:ubuntu pdflatex -interaction=nonstopmode -halt-on-error 2017-2018\ SE\ Paper.tex
before_deploy:
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - export GIT_TAG=$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
  - git push -q https://${GH_TOKEN}@github.com/vanderbiltrobotics/SystemsEngineeringPaper --tags
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: "KPx9Csodi734BMMR6pXro/6cPjss6mQwJa1j1q33QR4JhW7CH/qtN5w7wr+K9mPCgdn9HmxKUt6vgzuCIVnCG62buyI/qIiba6EOCxQukvh9VCcRRiWtsq0KohIBSTx2WUQKgztFTK1m66qNEzCP3cqtu1NtbzrKnGAXgK1AF8v/pIBIefS1JO9GHEJeMWXUAIn5mqseldquyfVhNhvlB74bVNhBsxq69hEtZ/VNdrWxl6JKWs2X71aO+qBbdrmMKge/AsFzy/zcSUOpPFq4xbGekljca6JHFExQfqczimoIZHauyhsFglhd2qGk7MzvvQSTJa/6G0Ga4zc8G295cO/1YQnMpbP1G2AjvS1es0otHGngmT0ltk+ZNFDs519r6Qp5IoebQ51FC/LEvaCO9TKRSV6v1NijfIvIJD9gX5mYCnVZu19mAdahzkoQvRyGbHKjPRMfFkr9LsrdNccw6dQlGC9GGpBRbN9TnbOmFNOEfjUByU/UjTML+fbzMonO/+g8IqMmNz9kXBBnOhG3s+Iph0i2SIdRIgayAtDBMdAowPmvYsMJFlrHnTrGRHizrpW50OMrlhF32+1kOLlpRBsnihWMZdsPVDXaoDF7HPd33zRJNIVMdE4wMlwH5kLJZvQ7z3zPj0n8Ylc+2q9ycPzvtat665VckgkExHJNKzc="
  file:
    - 2017-2018\ SE\ Paper.pdf
  on:
    tags: false
    all_branches: true
env:
  global:
    - secure: "WrwGGUGRUTYJO9nmbbvD6bVffXCaGRTUVvAmRKYcO93vYLjH6V6Nq2jj6LFJymJFNjQ1REGdkT5DPi36BWbaRiSfrGulz6kYLqvOKnRwpgqdmC2XmzcqDkfxDzeCXEAiDfZarFLW4WizPKQVtEVam/aOKN94ZCyhF+2H9v6xpxta/UEA7SMzblHPTAgcW57GNRcdoLChlz+zyQTompvPHJp3jvfYYMtvDu2czBBs9rsZtr2QSuchqrpQsyERF4y3ZThedmbekK+v4UReynfq0A8Gn1WlDqzILF11A9TDiA0yT/fSP/jFdcwhLDmLxeMkYVSt8IEaLVcpVpAlzHfLOK5yEijqCf34jPfDsh6FQsMZw/Cj5Dd3J/jK2LVdA+2s+WJIPX0f1SE7lhTjdllee6Lf0XsVjgsFlJxWCNJEH1A3DyiDnQywDfQPDZ9H19nKBajylDqmAgFP6/FK5kQ9w+/WZUCFpJlQZDrwTmHEmdR1QoP3UQBcVNqPW3OO0HgRtzePviwuKQASLZ7evawlEEspfj+L0op1fpwWNq6lOGm/++4AWVu7DZLbMSdCt/KShCf53IefJoqRFBD9iWIpJOIVbSF/vOUY6gk4Qi1nC8FEaNMbsUEPXNOLzMpD2J00Be/oleYbI/iYG+j56X4/2Xb6OAiUYeQeFjyAm8FncDw="
