sudo: required
dist: trusty
services:
- docker
before_install:
- docker pull blang/latex:ubuntu
script:
- docker run --rm --user="$(id -u):$(id -g)" --net=none -v "$PWD":/data blang/latex:ubuntu pdflatex -interaction=nonstopmode -halt-on-error 2017-2018\ SE\ Paper.tex
before_deploy:
- git config --global user.email "builds@travis-ci.com"
- git config --global user.name "Travis CI"
- export GIT_TAG=$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER
- git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
- git push -q https://jeholliday:$CIoluqTLYQg@github.com/vanderbiltrobotics/SystemsEngineeringPaper --tags
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: gcLPJTszVj2g/SrDKwlZj5dth/AEo2yDQ0ypvoweEsfXJZkAZpZeT6k6u5A4lSdS+j4PBnBa3w5iGG2IP9sLaqF7MyBJgZl/U6mSSvCQlN4lRU073c7O3XwFg98VnBPRUdoreeWLLAtjNwi+tXj1J5Iy+4wCHnwSIdpnfJGCgoy6e2+iQdynqY8NK4uDbzVE/iaQT8uVrfgN6yEwNc8J9X8lFtWJqPWJGTZs+dxyA0PxhzmJMup2UH/wiw/Fe7I8CoXn56Cva7NodxSzyzLCcwqcFe3sALi/+I1etycCs3InsqnnLYPQ8TDRGChvjOM7dxHeZBjNOoMBwsV6nl85GplVTavUC8WqQZg6VJDGQFX++d0Q7jomf7mNph4I8yd0GwKJrUzM/4k1psntJfVRe2V5Gh6fXbs3ru6nWL2VL85OrDKw039KezM0CfZQyOakfuClzOTSxO+oVnu8YMYQZ5zzOKMZS5TuuxNaVAfSlTygXfz62o7U1V++rgpw3d1bgDO4kZmAISiTeWnEMQ7bothMnki678CMAsdyXlKPVAopN2FBCiZSj2yKC0pYfbjxcSgAxUt6uvw1rNVyFK75Gh2ppn5vtd19qgu/0qEfHmpPrdWOeE2atlOKZFGTqktMlQ0NZm9otBnKb8YqXk6oBEsF4lGMM9ITIFoyuRYqulI=
  file:
  - 2017-2018\ SE\ Paper.pdf
  on:
    tags: false
    all_branches: true
env:
  global:
    secure: q6/X/7P2Th12wM5j9TCTdFTGgdOEG8/yhRUzQxYCgum3+MY/gMeVC3dl/+f3cmnui1ljs0ZLz/+tZzAsa8Ozc3jBJU+RQugwGgtgrh2XiNOBPqtzgAWHJRrSffgPHJ7aJDb7a0ZLa67OfHWsGnUTqqLSOTuA/sqQNykp9oCI1RHRflBCqCDymV2hAQGVGvL4ynViPO6ARWy6/sMYeZcsvxtBBThO++A2xiR/95iBiaKAGA9LntFNyAm3R8DDaZmIWK42uoY5A+VoOiMRWY8j9UQP6GO6tYp7Uwb8heSB1BdymmD89izGWagAraOjmZzY2xiWvuws/TqcxhFfzqwyu8O24bH3tgdMmhuQBGolpr3eAazH3W0NNsIhjsADZN53Qhk1/wfb0dhnO05l39hZgs6LhfJBBqy2b73fsf4sp+aGTUuUqw6m7uByyD2OKcqp+3iWWuQjOzLSLhTXNGZHuox1cUSmjk6c/7wgqjpBZEg7CBQzrDN9u89u2ZRlwc0+46gQtLym5HP5yKsGtEWAjj+T426ByPM9QmVuhuvuWqcGh5VbIZxCHqFWDF9uR9Zlinv+r+aIKfwMtsHbsyqebIIOwOwiXDUrPogVlTu8l9/K167L4aNeNUZ0C9qG+uyy1E5jWtPplnsW+O3utvXeigE/pxzM3Ti/CIoluqTLYQg=
